### ISSUE TITLE
Refactor for async

### ISSUE THREAD

**Issue by AnandChowdhary** [denorg/is-docker#1]
I'd highly recommend refactoring for async by default; we don't want to block up any threads.

Maybe it's a good idea to use `readFile` instead of `readFileSync`, so people can use it like:

```ts
await isDocker(); // // boolean
```

rather than

```ts
isDocker(); // boolean
```

If you like, you can add a sync method, `isDockerSync`:

```ts
import { isDocker, isDockerSync } from "...path/to/isdocker";

const withoutSync = await isDocker(); // boolean
const withSync = isDockerSync(); // boolean
```

**Comment by yg** [comment]
Thanks, @AnandChowdhary for suggestions, I will work on it today :unicorn:

**Comment by yg** [comment]
We can Implement `isDockerSync` little latter, it tends to increase the code size!
